# Copyright (c) 2026, modmesh contributors
# BSD-style license; see COPYING

import argparse
from dataclasses import dataclass
from pathlib import Path
from textwrap import dedent


def block(text):
    return dedent(text).strip("\n") + "\n"


@dataclass(frozen=True)
class GeneratorConfig:
    benchmark_cases: tuple[tuple[int, int], ...] = (
        (100, 10_000),
        (1_000, 1_000),
        (10_000, 5),
        (50_000, 1),
    )
    operation_counts: tuple[int, ...] = (100, 1_000, 10_000, 50_000)
    max_call_count: int = 50_000
    repeated_visit_count: int = 100
    default_shard_count: int = 32
    namespace: str = "modmesh::profiling"
    detail_namespace: str = "modmesh::profiling::detail"
    prologue: str = """\
/*
 * Generated by profiling/cprof/generate_workload.py.
 * Do not edit manually.
 */

"""


class GeneratedFileWriter:
    def __init__(self, output_dir, config):
        self.output_dir = output_dir
        self.config = config

    @staticmethod
    def function_name(index):
        return f"profile_empty_{index:06d}"

    def write_generated(self, filename, content):
        path = self.output_dir / filename
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(self.config.prologue + content, encoding="utf-8")


class FunctionHeaderGenerator(GeneratedFileWriter):

    def generate(self):
        declarations = "".join(
            f"void {self.function_name(index)}"
            "(std::size_t begin, std::size_t end);\n"
            for index in range(self.config.max_call_count)
        )
        detail_namespace = self.config.detail_namespace
        self.write_generated(
            "callprofiler_workload_functions.hpp",
            block(f"""
            #pragma once

            #include <callprofiler_workload.hpp>

            namespace {detail_namespace}
            {{
            """)
            + declarations
            + block(f"""
            }} /* namespace {detail_namespace} */
            """),
        )


class RunnerSourceGenerator(GeneratedFileWriter):
    public_template = block("""
    namespace
    {
    void validate_size(std::size_t size)
    {
        if (size == 0 || @max_call_count@ < size)
        {
            throw std::invalid_argument("unsupported cprof size");
        }
    }
    void set_shape(detail::WorkloadShape shape, std::size_t size)
    {
        validate_size(size);
        detail::active_shape = shape;
        detail::active_size = size;
    }
    } /* namespace */
    MODMESH_CPROF_NOINLINE void run_wide_siblings(std::size_t size)
    {
        MODMESH_PROFILE_FUNCTION();
        set_shape(detail::WorkloadShape::flat, size);
        for (std::size_t index = 0; index < size; ++index)
        {
            detail::call_profile_function(index, 0, 0);
        }
    }
    MODMESH_CPROF_NOINLINE void run_deep_chain(std::size_t size)
    {
        MODMESH_PROFILE_FUNCTION();
        set_shape(detail::WorkloadShape::list, size);
        detail::call_profile_function(0, 0, 0);
    }
    MODMESH_CPROF_NOINLINE void run_balanced_tree(std::size_t size)
    {
        MODMESH_PROFILE_FUNCTION();
        set_shape(detail::WorkloadShape::tree, size);
        std::size_t const root = size / 2;
        detail::call_profile_function(root, 0, size);
    }
    MODMESH_CPROF_NOINLINE void run_hot_name_reuse(std::size_t size)
    {
        MODMESH_PROFILE_FUNCTION();
        validate_size(size);
        std::size_t const width = size / @repeated_visit_count@;
        detail::active_shape = detail::WorkloadShape::flat;
        detail::active_size = width;
        @repeat_loop@
        {
            for (std::size_t index = 0; index < width; ++index)
            {
                detail::call_profile_function(index, 0, 0);
            }
        }
    }
    """)

    def function_table(self):
        entries = "".join(
            f"    &{self.function_name(index)},\n"
            for index in range(self.config.max_call_count)
        )
        return (
            "std::array<profile_function_type, "
            f"{self.config.max_call_count}> const profile_functions = "
            "{{\n"
            f"{entries}"
            "}};\n\n"
            "void call_profile_function(std::size_t index, "
            "std::size_t begin, std::size_t end)\n"
            "{\n"
            "    profile_functions[index](begin, end);\n"
            "}\n"
        )

    def generate(self):
        detail_section = (
            "WorkloadShape active_shape = WorkloadShape::flat;\n"
            "std::size_t active_size = 0;\n\n"
            f"{self.function_table()}"
        )
        public_section = (
            self.public_template
            .replace("@max_call_count@", str(self.config.max_call_count))
            .replace(
                "@repeat_loop@",
                "for (std::size_t repeat = 0; "
                f"repeat < {self.config.repeated_visit_count}; ++repeat)",
            )
            .replace(
                "@repeated_visit_count@",
                str(self.config.repeated_visit_count),
            )
        )
        detail_namespace = self.config.detail_namespace
        namespace = self.config.namespace
        self.write_generated(
            "callprofiler_workload.cpp",
            block(f"""
            #include <callprofiler_workload.hpp>
            #include <callprofiler_workload_functions.hpp>

            #include <array>
            #include <stdexcept>

            namespace {detail_namespace}
            {{
            """)
            + detail_section
            + block(f"""
            }} /* namespace {detail_namespace} */

            namespace {namespace}
            {{
            """)
            + public_section
            + block(f"""
            }} /* namespace {namespace} */
            """),
        )


class ShardSourceGenerator(GeneratedFileWriter):
    function_template = block("""
    @signature@
    {
        MODMESH_PROFILE_FUNCTION();
        if (WorkloadShape::list == active_shape)
        {
            constexpr std::size_t next = @next@;
            if (next < active_size)
            {
                call_profile_function(next, 0, 0);
            }
        }
        else if (WorkloadShape::tree == active_shape)
        {
            std::size_t const middle = begin + (end - begin) / 2;
            if (begin < middle)
            {
                std::size_t const left_middle = begin + (middle - begin) / 2;
                call_profile_function(left_middle, begin, middle);
            }
            std::size_t const right_begin = middle + 1;
            if (right_begin < end)
            {
                @right_middle@
                call_profile_function(right_middle, right_begin, end);
            }
        }
    }
    """)

    def function_definition(self, index):
        signature = (
            "MODMESH_CPROF_NOINLINE MODMESH_CPROF_NOINST void "
            f"{self.function_name(index)}"
            "(std::size_t begin, std::size_t end)"
        )
        return (
            self.function_template
            .replace("@signature@", signature)
            .replace("@next@", str(index + 1)) + "\n"
        ).replace(
            "@right_middle@",
            "std::size_t const right_middle = "
            "right_begin + (end - right_begin) / 2;",
        )

    def shard_indices(self, shard_count):
        return [
            list(range(shard_index, self.config.max_call_count, shard_count))
            for shard_index in range(shard_count)
        ]

    def generate(self, shard_count):
        detail_namespace = self.config.detail_namespace
        for shard_index, indices in enumerate(self.shard_indices(shard_count)):
            shard_content = "".join(
                self.function_definition(index) for index in indices
            )
            self.write_generated(
                f"callprofiler_workload_{shard_index}.cpp",
                block(f"""
                #include <callprofiler_workload.hpp>

                namespace {detail_namespace}
                {{
                """)
                + shard_content
                + block(f"""
                }} /* namespace {detail_namespace} */
                """),
            )


class WorkloadGenerator:

    def __init__(self, output_dir, config):
        self.output_dir = output_dir
        self.config = config

    def generate(self, shard_count):
        self.validate(shard_count)
        FunctionHeaderGenerator(self.output_dir, self.config).generate()
        RunnerSourceGenerator(self.output_dir, self.config).generate()
        ShardSourceGenerator(self.output_dir, self.config).generate(
            shard_count
        )

    def validate(self, shard_count):
        if shard_count < 1:
            raise ValueError("--shards must be positive")
        if any(
            size % self.config.repeated_visit_count
            for size in self.config.operation_counts
        ):
            raise ValueError("case sizes must divide repeated visits")


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument(
        "--shards",
        type=int,
        default=GeneratorConfig().default_shard_count,
    )
    return parser.parse_args()


def main():
    args = parse_args()
    generator = WorkloadGenerator(args.output_dir, GeneratorConfig())
    generator.generate(args.shards)


if __name__ == "__main__":
    main()

# vim: set ff=unix fenc=utf8 et sw=4 ts=4 sts=4:
