name: CodeCov

on:
    pull_request:

env:
    CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

jobs:
    check_coverage:

        runs-on: ubuntu-latest

        strategy:
            matrix:
                os: [ubuntu-22.04]
                cmake_build_type: [Release]

        steps:

            - uses: actions/checkout@v2

            - name: event name
              run: |
                echo "github.event_name: ${{ github.event_name }}"

            - name: dependency by apt
              run: |
                VERSION_ID=$(bash -c 'source /etc/os-release ; echo $VERSION_ID')        
                if [ "20.04" == "$VERSION_ID" ] ; then CLANG_TIDY_VERSION=10 ; else CLANG_TIDY_VERSION=14 ; fi
                sudo apt-get -qqy update
                sudo apt-get -qy install \
                    sudo curl git build-essential make cmake libc6-dev gcc g++ silversearcher-ag \
                    clang-tidy-${CLANG_TIDY_VERSION} \
                    python3 python3-dev python3-venv
                sudo ln -fs "$(which clang-tidy-${CLANG_TIDY_VERSION})" "$(dirname $(which clang-tidy-${CLANG_TIDY_VERSION}))/clang-tidy"
                # Install qt6 only with ubuntu-22.04
                # This page explains why we need libgl1-mesa-dev
                # https://doc-snapshots.qt.io/qt6-dev/linux.html
                #
                # In short, OpenGL libraries and headers are required. Without
                # installing this package, cmake won't find out the correct lib path.

                if [ "${{ matrix.os }}" == "ubuntu-22.04" ] ; then \
                sudo apt-get -qy install \
                    qt6-3d-dev xvfb \
                    libgl1-mesa-dev
                fi

            - name: dependency by pip
              run: |
                sudo pip3 install setuptools
                sudo pip3 install numpy pytest coverage pytest-cov flake8 pyside6==$(qmake6 -query QT_VERSION)

            - name: dependency (manual)
              run: sudo ${GITHUB_WORKSPACE}/contrib/dependency/install.sh pybind11

            - name: show dependency
            # Copy the commands from contrib/dependency/showdep.sh
              run: |
                echo "gcc path: $(which gcc)"
                echo "gcc version: $(gcc --version)"
                echo "cmake path: $(which cmake)"
                echo "cmake version: $(cmake --version)"
                echo "python3 path: $(which python3)"
                echo "python3 version: $(python3 --version)"
                echo "pip3 path: $(which pip3)"
                python3 -c 'import numpy ; print("numpy.__version__:", numpy.__version__)'
                echo "pytest path: $(which pytest)"
                echo "pytest version: $(pytest --version)"
                echo "clang-tidy path: $(which clang-tidy)"
                echo "clang-tidy version: $(clang-tidy -version)"
                echo "flake8 path: $(which flake8)"
                echo "flake8 version: $(flake8 --version)"

            - name: make cinclude (check_include)
              run: make cinclude

            - name: make buildext BUILD_QT=OFF
              run: |
                rm -f build/*/Makefile
                make cmake \
                  VERBOSE=1 USE_CLANG_TIDY=OFF \
                  BUILD_QT=OFF \
                  CMAKE_BUILD_TYPE=${{ matrix.cmake_build_type }} \
                  CMAKE_ARGS="-DPYTHON_EXECUTABLE=$(which python3)"
                make buildext VERBOSE=1
        
            - name: make pytest COVERAGE=ON BUILD_QT=OFF
              run: |
                python3 -c "import modmesh; assert modmesh.HAS_VIEW == False"
                make pytest COVERAGE=ON VERBOSE=1
                
            - name: Upload coverage reports to Codecov with GitHub Action
              uses: codecov/codecov-action@v3
